channels:
- conda-forge
dependencies:
  #https://anaconda.org/search  
- python=3.7.5
- pip=20.1
- pip:
  - rpaframework==11.3.0
  - robotframework-browser==8.0.2
  - nodejs==14.17.4
rccPostInstall:
- rfbrowser init